name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: github
          POSTGRES_DB: github_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U github -d github_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: github_test
      DB_USER: github
      DB_USER_PASSWORD: github
      DB_HOST: localhost

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --system

      - name: Wait for Postgres
        run: |
          until pg_isready -h $DB_HOST -p 5432 -U $DB_USER; do
            sleep 1
          done

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
